manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ggrocer
      url-base: https://github.com/greengrocer98
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-paw3395-driver
      remote: ggrocer
      revision: main
    - name: zmk-vfx-rgbled-indicator
      remote: ggrocer
      revision: main
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      revision: main
  self:
    path: config